server:
  port: 8080  # 服务端口号

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&autoReconnect=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&allowMultiQueries=true  # 数据库地址
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 8.0 及以上需要 cj，5.7 以下可去掉 cj
    username: root  # 数据库用户名
    password: abc123  # 数据库密码
    type: com.alibaba.druid.pool.DruidDataSource  # 使用 Druid 数据源
    druid:
      # 连接池基本配置
      initial-size: 5  # 初始化连接数
      min-idle: 10  # 最小空闲连接数
      max-active: 20  # 最大连接数
      max-wait: 60000  # 最大等待时间（毫秒）
      time-between-eviction-runs-millis: 60000  # 多少毫秒执行一次空闲连接回收
      min-evictable-idle-time-millis: 300000  # 连接最小生存时间（毫秒）
      max-evictable-idle-time-millis: 1200000  # 连接最大生存时间（毫秒）

      # 连接校验配置
      validation-query: SELECT 1  # 用于测试连接是否可用的 SQL 语句
      validation-query-timeout: 2000  # SQL 校验超时时间（毫秒）
      test-on-borrow: false  # 获取连接时是否检测（影响性能，建议关闭）
      test-on-return: false  # 归还连接时是否检测（影响性能，建议关闭）
      test-while-idle: true  # 空闲时是否检测（推荐开启）

      # 连接池优化配置
      phy-max-use-count: 1000  # 每个连接的最大使用次数
      pool-prepared-statements: false  # 是否开启 PSCache
      max-open-prepared-statements: 50  # PSCache 允许的最大预编译 SQL 数

      # Druid 监控配置
      filters: stat,wall,log4j2  # 启用监控统计拦截的过滤器（SQL监控、防火墙、日志）

      # 监控页面配置
      stat-view-servlet:
        enabled: true  # 启用内置监控页面
        url-pattern: /druid/*  # 监控页面路径
        login-username: admin  # 访问监控页面的用户名
        login-password: admin  # 访问监控页面的密码
        reset-enable: false  # 是否允许重置统计数据
        allow: 127.0.0.1  # 允许访问的 IP 白名单
        deny: 192.168.0.1  # 禁止访问的 IP 黑名单

      # Web 监控配置
      web-stat-filter:
        enabled: true  # 开启 Web-JDBC 关联监控
        url-pattern: /*  # 监控所有请求
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"  # 排除静态资源和监控路径
        session-stat-enable: true  # 启用 Session 统计
        session-stat-max-count: 1000  # Session 最大数量

      # SQL 慢查询日志配置
      filter:
        stat:
          # 是否开启 FilterStat，默认true
          enabled: true
          # 是否开启 慢SQL 记录，默认false
          log-slow-sql: true
          # 慢 SQL 的标准，默认 3000，单位：毫秒
          slow-sql-millis: 5000
          # 合并多个连接池的监控数据，默认false
          merge-sql: false

        # 日志配置，采用 SLF4J
        slf4j:
          enabled: true  # 启用日志
          statement-log-error-enabled: true  # 开启 SQL 语句错误日志
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG  # 开启 SQL 执行日志

mybatis-plus:
  # MyBatis Plus 配置
  mapper-locations: classpath:mapper/*.xml  # Mapper XML 文件路径
  configuration:
    auto-mapping-behavior: full  # 自动映射策略
    map-underscore-to-camel-case: true  # 开启驼峰命名转换
    call-setters-on-nulls: true  # 结果中包含 null 时仍然映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台输出 SQL 日志
